export const LEVEL_ONE = [
  "What do you think is the hardest part of what I do for a living?",
  "What reality show do you think I&apos;m most likely to binge watch? Explain.",
  "What&apos;s the first thing you noticed about me?",
  "If Myspace was still a thing what would my profile song be?",
  "If you were to buy me a present, knowing nothing about me other than what I look like, what would it be?",
  "Do you think plants thrive or die in my care? Explain.",
  "Do I look kind? Explain.",
  "Do I seem like more of a creative or analytical type? Explain.",
  "Finish the sentence: Just by looking at you I&apos;d think _____________.",
  "What do my shoes tell you about me?",
  "Do you think I&apos;ve ever been fired from a job? If so, what for?",
  "What was your first impression of me?",
  "How would you describe what you think my type is in three words?",
  "Between the two of us, who seems like the better texter? Explain.",
  "What does my Instagram tell you about me?",
  "Make an assumption about me",
  "What about me intrigues you?",
  "What do you think I&apos;m most likely to splurge on?",
  "As a child, what do you think I wanted to be?",
  "Do you think I was popular in school? Explain.",
  "Do I seem like someone who would get a name tattooed on myself? Why or why not?",
  "Do you think I fall in love easily why or why not",
  "What compliment do you think I hear the most?",
  "Do you think I ever checked an Ex phone for evidence?",
  "What subject do you think I thrived at in school and did I fail any?",
  "Do I seem like a coffee or tea person - sweetened or unsweetened?",
  "Do I seem like a morning person or a night owl?",
  "Do you think I was popular at school? Explain.",
  "Do you think I&apos;m usually early on time or late to events. Explain.",
  "Am I someone you typically connect with?",
  "Do I intimidate you? Why or why not?",
];

export const LEVEL_TWO = [
  "What&apos;s been your happiest memory this past year?",
  "Have you changed your mind about anything recently?",
  "What has been your earliest recollection of happiness?",
  "What lesson took you the longest to un-learn?",
  "Are you lying to yourself about anything?",
  "What questions are you trying to answer most in your life right now?",
  "When was the last time you surprised yourself?",
  "What title would you give this chapter in your life?",
  "Finish the sentence: Strangers would describe me as ______ only I know that I am _______",
  "What&apos;s the worst pain you have ever been in that wasn&apos;t physical?",
  "Has a stranger ever changed your life?",
  "What&apos;s your first loves name and the reason you fell in love with them?",
  "What would your younger self not believe about your life today?",
  "How would you describe the feeling of being in love with one word?",
  "What are you more afraid of: failure or success and why?",
  "What is a dream you let go of?",
  "If you could get to know someone in your life on a deeper level who would it be and why?",
  "What part of your life works what part of your life hurts?",
  "How can you become a better person?",
  "Do you think the image you have of yourself matches the image other people see you as?",
  "Are you missing anyone right now? Do you think they miss you to?",
  "What fast food restaurant do you think I&apos;m most likely to drive through? What&apos;s my order?",
  "Do you think I intimidate others? Why or why not?",
  "When you are asked how are you, how often do you answer truthfully?",
  "How are you, really?",
  "What&apos;s the most unexplainable thing that happened to you?",
  "If you could have it your way: who would you be with? Where would you be? What would you be doing?",
  "Describe your perfect day!",
  "What dating advice would you give your younger self?",
  "How old do you feel emotionally?",
  "What&apos;s the most embarrassing thing that happened to you on a date?",
  "What could you have done better in previous relationships?",
  "Is there an image of yourself you try to project on a first date you wish you could let go of?",
  "Finish the sentence: Dating is ____________ (both players)",
  "What did the people who raised you teach you about love?",
  "What has being single taught you about yourself?",
  "What&apos;s your least favorite question to be asked on a date? What do you wish you would be asked more?",
  "What are you passionate about?",
  "What are you not currently giving enough time to?",
  "What about my profile made you swipe right?",
];

export const LEVEL_THREE = [
  "What about me surprised you?",
  "What do you think our most important similarities are?",
  "What do you think is one thing I could do that would drastically improve my life?",
  "What would be the perfect gift for me?",
  "What do I need to hear right now?",
  "What is a lesson you will take away from our conversation?",
  "What do you think do I fear the most?",
  "Where am I most qualified to give advice about?",
  "What about me is the hardest for you to understand?",
  "Admit something.",
  "How does one earn your vulnerability?",
  "What do you recommend I should let go of?",
  "What has this conversation taught you about yourself?",
  "What do you think my defining characteristic is?",
  "What question were you most afraid to answer?",
  "What do you think my weakness is?",
  "What do you think I should know about myself that perhaps I&apos;m unaware of?",
  "What would make you feel closer to me?",
  "What do you admire most about me?",
  "In one word, describe how you feel right now.",
  "What can we create together?",
  "What&apos;s the most attractive quality about me that isn&apos;t physical?",
  "Am I like you expected me to be?",
];

export const LEVEL_ONE_DATING = [
  "How many relationships do you think I&apos;ve been in?  How many times do you think I&apos;ve been in love? Explain",
  "Just by looking at me, what would you think I do for a living?",
  "What was the first thing you noticed about me when we met in person?",
  "What do you think my type is? Describe in detail.",
  "What do you think I was like in high school? Explain.",
  "Do you think I&apos;m still on good terms with my exes? Why or why not?",
  "When&apos;s the last time you ghosted someone and why?",
  "What about me intrigued you besides my physical appearance?",
  "What do your friends know about me, if anything?",
];

export const LEVEL_TWO_DATING = [
  "What are you feeling a lot of lately?",
  "Do you have any unconventional opinions when it comes to romantic relationships?",
  "I know I really like someone when ______.",
  "How has your view on love evolved over time, if at all?",
  "Describe your worst heartbreak. What did it teach you?",
  "Who in your life do you feel most yourself around? Why?",
  "What is something new you&apos;ve learned about yourself recently?",
  "How do you define “Dating”?",
  "Have you ever considered an open relationship? Why or why not?",
  "What&apos;s the hardest part about dating you?",
  "What dating advice would you give your younger self?",
  "What was the worst date you&apos;ve ever been on and why?",
  "What are you overthinking right now?",
  "What have you tolerated from others in the past that you no longer have space for?",
  "How emotionally available do you currently feel? Explain.",
  "What has being single taught you about yourself?",
  "What about you has felt repeatedly misunderstood by others, if anything?",
  "What&apos;s a non-negotiable in your life?",
  "What did the people who raised you teach you about love? How has that shaped your views on love today?",
  "Based on what you&apos;ve learned about me, what do you think I&apos;m looking for romantically?",
  "What mannerisms of mine stood out the most to you? If any?",
  "If you were to write my dating profile bio, what would it say?",
];

export const LEVEL_THREE_DATING = [
  "On a scale of 1-10, how “emotionally available” do I seem? Explain.",
  "How would you describe our date in one word?",
  "Which part of my personality isn&apos;t showcased online?",
  "What do you find most attractive about me that isn&apos;t physical?",
];
